how_mas_core_ms:
    document:
        listing:
            showRoots: true # hide or show document root while listing data
    # object:
    #     listing:
    #         condition: # add condition while listing data
    #             blog:
    #                 query_string: 'image != :image'
    #                 condition_array:
    #                     'image': 0
    ecommerce:
        enable: true
        classes:
            category: Category
            products:
                - Product
            order: OnlineShopOrder
            # others:
            #     - Customer
    template:
        form:
            numeric:
                js_masked:
                    enable: true
                    template: "#,##0"

    # system:
    #     admin:
    #         access_core_names:
    #             - admin
