# pimcore_admin_index:
#     path: '/admin'
#     controller: HowMAS\CoreMSBundle\Controller\DefaultController::redirectAction
#     methods: GET

how_mas_core_ms_default:
    resource: "@HowMASCoreMSBundle/src/Controller/*"
    type: annotation
    prefix: /admin/hcore
    name_prefix: 'hcore-'
